### ISSUE TITLE
Can someone make a dark theme for this web app? A black background will also do. 

### ISSUE THREAD

**Issue by SarthakRana** [SarthakRana/Covid-19-Dashboard#1]
I am looking to convert the background of this dashboard/ web app from default white to black. Like a black theme.

**Comment by cromatikap** [comment]
I'm up to work on this.

**Comment by nimit2801** [comment]
I'll 

> 
> 
> I am looking to convert the background of this dashboard/ web app from default white to black. Like a black theme.

I'll help with this 👍

**Comment by symtalha14** [comment]
Please assign it to me. I'll add a toggle functionality for dark mode/light mode.

**Comment by SarthakRana** [comment]
Hi @bidetaggle  @Nimit1428  @symtalha14 . Please go ahead. I would love to see what you guys come up with 👍

**Comment by manish-pritmani** [comment]
I will love to work on this.

**Comment by cromatikap** [comment]
> Hi @bidetaggle @Nimit1428 @symtalha14 . Please go ahead. I would love to see what you guys come up with 👍

Then I let you go on this guys :)

**Comment by SarthakRana** [comment]
@manish-pritmani Sure buddy.
